### PR TITLE
Change react-native-touch-id to expo-local-auth

### PR DESCRIPTION
**Pull request by Volekss**
This PR changes `react-native-touch-id` library to `expo-local-authentication` in order to use biometrics

### CODE REVIEW

**Comment by DDushkin** [comment]
Снимок экрана 2023-01-17 в 13 45 0
@Volekss have you tested it?

**Comment by Volekss** [comment]
@DDushkin I did, but this seems to be some last-minute change before making a commit, somehow it got there, let me remove the double `()()`

**Comment by DDushkin** [comment]
@Volekss but you cannot just edit dist folder, it is autogenerated from ts

**Comment by Volekss** [comment]
> @Volekss but you cannot just edit dist folder, it is autogenerated from ts

well I did exactly that, I changed dist and ts folders

**Comment by DDushkin** [comment]
> > @Volekss but you cannot just edit dist folder, it is autogenerated from ts
> 
> 
> 
> well I did exactly that, I changed dist and ts folders

Project should be compiled with `yarn build`. Not by manual changes

**Comment by Volekss** [comment]
> > > @Volekss but you cannot just edit dist folder, it is autogenerated from ts
> > 
> > 
> > well I did exactly that, I changed dist and ts folders
> 
> Project should be compiled with `yarn build`. Not by manual changes

Just did it

**Pull request merged**
